/* DEFAULT BLOC VALUES */
ALTER TABLE categories ALTER blocDebut SET DEFAULT 0;
ALTER TABLE categories ALTER blocFin SET DEFAULT 95;

/* BLOC DOMAIN ON CATEGORIE */
DROP DOMAIN IF EXISTS blocDomain;
CREATE DOMAIN blocDomain AS INTEGER CHECK(VALUE BETWEEN 0 and 95);
ALTER TABLE categories ALTER COLUMN blocDebut SET DATA TYPE blocDomain;
ALTER TABLE categories ALTER COLUMN blocFin SET DATA TYPE blocDomain;

/* BLOC DOMAIN ON BLOCTEMPSPOSSIBLE */
ALTER TABLE bloctempspossible ALTER COLUMN bloctempsid SET DATA TYPE blocDomain;

/* BLOC DOMAIN ON RESERVATION */
ALTER TABLE reservations ALTER COLUMN numerobloc SET DATA TYPE blocDomain;

/* RENAME LOCAUX COLUMNS */
ALTER TABLE locaux RENAME LOC_NUMEROPAVILLON TO NUMEROPAVILLONPARENT;
ALTER TABLE locaux RENAME LOC_NUMEROLOCAL TO NUMEROLOCALPARENT;

/* CHANGE LOGS COLUMN TYPE */
ALTER TABLE logs ALTER COLUMN logdate TYPE TIMESTAMP;

/* CHANGE CONSTRAINT OF EVENT TO CASCADE DELETE */
ALTER TABLE public.reservations DROP CONSTRAINT fk_reservat_evenement_evenemen;
ALTER TABLE public.reservations
  ADD CONSTRAINT fk_reservat_evenement_evenemen FOREIGN KEY (evenementid)
    REFERENCES evenements (evenementid)
      ON DELETE CASCADE ON UPDATE RESTRICT;


/* TRUNCATE ALL TABLES FUNCTION */
CREATE OR REPLACE FUNCTION truncate_all_tables() RETURNS void AS $$
DECLARE
    statements CURSOR FOR
        SELECT tablename FROM pg_tables
        WHERE schemaname = 'public';
BEGIN
    FOR stmt IN statements LOOP
        EXECUTE 'TRUNCATE TABLE ' || quote_ident(stmt.tablename) || ' CASCADE;';
    END LOOP;
END;
$$ LANGUAGE plpgsql;
